### ISSUE TITLE
Figuring out the flow to the login page

### ISSUE THREAD

**Issue by maraymer** [elanderson/Angular-Core-IdentityServer#11]
@elanderson 

I was happy to find your blog and this project in GitHub.

I'm currently implementing an Angular application that needs to use IdentityServer4 collecting username and password as well as accepting other OIDC providers (in my initial case only Facebook). 

It looks like what you've got written almost does all that already (of course, without Facebook and there are several other requirements I'll have to add to IdentityServer but the stub requirements are there).

One of my requirements is to fully understand whatever I implement :-)

So, with that in mind, I wanted to know how the Angular application knows which Url to load a login window on the OIDC provider?

Looking through the code I can see that angular-auth-oidc-client module is included.  And that whenever the Angular application calls its login() (in navMenu.component.tst) that it references authService.login which ultimate references oidcSecurityService.authorize()!

Then in oidcSecurityService.authorize() it generates a url by calling createAuthorizeUrl.  That url ultimately gets stuffed into a window.location.href which initiates my first question:

*Is this a window which triggers a popup akin to the Facebook popup login page?*

My last question(s) is about the url itself.  When I look at createAuthorizeUrl, the first thing that I notice is that it uses this.authWellKnownEndpoints.authorization_endpoint which I know it is getting from querying IdentityServer ala OIDC discovery protocol. 

*When I look into IdentityServer, I do not see IdentityServer it defines an actual login page url?*

In my own project's .well-known/openid-configuration results, authorization_endpoint contains  "http://localhost:5000/connect/authorize" which I assume is a standard address.  I've looked around the Config.js of the IdentityServer and this only makes me more perplexed :-) The RedirectUrl of the mvc and ng clients are http://localhost:5002/signin-oidc and http://localhost:5002/callback respectively.  

Thanks in advance.  Your series is probably been one of the most useful (in the top 3 of the dozens I've reviewed).

Matthew

**Comment by elanderson** [comment]
@maraymer I have been out of town and will have to do some research to see if I can find answers to your questions. If you do find the answers before I can I would appreciate hearing your findings.

In a future post, I change OIDC clients to this [one](https://github.com/damienbod/angular-auth-oidc-client) which was created specifically for Angular (4+), and certified by Open ID Connect,  which recommend you check out.

Thank you for the kind words about my series I really appreciate it!

**Comment by maraymer** [comment]
@elanderson Awesome!  Actually, I was already looking at the version using angular-auth-oidc-client when I asked the question.  My plan in the next hour or so is to clone that version and try doing some tests locally.  I'll keep you posted how this turns out.

**Comment by maraymer** [comment]
@elanderson Looks like I'll have to do some work here to get it to compile :-)

**Comment by maraymer** [comment]
@elanderson 

Ah!  I now see with your new article that I'm two tags ahead of your current development!  When I run the TaskRunner in v0.9.0 I get ...

ERROR in [at-loader] ./ClientApp/boot-server.ts:36:7 
        TS2304: Cannot find name 'BootFunc'.

Any idea what I'm doing wrong?

**Comment by elanderson** [comment]
Yes, I believe that is a Typescript related issue. If you look at the one in my repo you will see that everything inside of createServerRenderer is wrapped in parentheses and cast as BootFunc. See if that fixes your compile issues.

`export default createServerRenderer((params => { ....
}) as BootFunc);`

**Comment by maraymer** [comment]
@elanderson That's actually what I'm seeing in the v0.9.0 branch ./ClientApp/boot-server.ts:36 and the TaskRunner is reflecting that error still?

**Comment by elanderson** [comment]
@maraymer maybe it has been fixed and is no longer needed? What if you unwrap the function?

What version of Typescript are you using?

Another thing that will some times clear up issues is running the following from the command line in the project directory just to make sure the vendor.js is up to date.

`webpack --config webpack.config.vendor.js --env.prod`

**Comment by maraymer** [comment]
VS command prompt output for tsc -v is 2.2.3
I'll try to unwrap it now

**Comment by maraymer** [comment]
@elanderson 
Removing the BootFunc seems to have worked.  Easy solution!  Now, let me see if I can run the client

**Comment by maraymer** [comment]
@elanderson Client runs.

**Comment by maraymer** [comment]
OK.  Well, the app loads and I've done the the web pack vendor update.  It's blowing up when you click on the Login link in the client ..

Current window: localhost/login
SCRIPT5009: 'vendor_b7199ba5a0e681456630' is undefined
main-client.js (79,1)

I'll keep digging

**Comment by maraymer** [comment]
@elanderson  Got it running by reruning the TaskRunner.  Ran into CSP errors which I've blocked for the time-being.  I think this almost gets me ready to work with the Angular APp :-)

**Comment by elanderson** [comment]
@maraymer glad you got mostly up and running! 

I am hoping to get enough time to research your initial questions sometime this week. I can answer 

> Is this a window which triggers a popup akin to the Facebook popup login page?

In the default setup the login isn't a popup but a full page. IdentityServer is pretty flexible and I bet there is away to do a Facebook style popup, but I haven't looked in to it yet.

**Comment by maraymer** [comment]
@elanderson I think you are correct about the popup.  It'll be one of my major goals this week.  I'm moving everything over to EntityFrameworkCore in the IdentityServer.  I'll be sure to tell you how the work goes and I can probably share some of the things accomplished.

**Comment by elanderson** [comment]
@maraymer I have done a little bit of digging and the http://localhost:5000/.well-known/openid-configuration endpoint is part of the OpenID Connect Discovery [spec](https://openid.net/specs/openid-connect-discovery-1_0.html). The values that Identity Server returns seem to be the standard values.

As for how the login page route is handled in Identity Server look [here](https://github.com/IdentityServer/IdentityServer4/blob/bfae2858aa01174d938c84f0871bb7b15786bd63/src/IdentityServer4/Endpoints/Results/LoginPageResult.cs) and search for LoginUrl.

**Comment by elanderson** [comment]
@maraymer a bit more information the Angular client I switched to doesn't have a popup option for login, but I did find that [oidc-client](https://github.com/IdentityModel/oidc-client-js/blob/dev/sample/public/user-manager-sample-popup-signin.html) does if that is a requirement you have.

**Comment by maraymer** [comment]
@elanderson thanks.  Thanks for the link!  I'll take a look at that today.

**Comment by maraymer** [comment]
@elanderson Ah!  So obvious now.  This can be ported over to angular-auth-oidc-client with a little study of their existing structure.  Thanks.

**Comment by elanderson** [comment]
That is great news! If you are going to do that work check out [this ](https://github.com/damienbod/angular-auth-oidc-client/issues/24)issue I am sure damienbod would be happy to have the contribution.

I am going to close this issue for now, but fill free to reopen or add a new one if you have any more questions or updates.

**Comment by maraymer** [comment]
@elanderson thanks!  I'll note that.  We may have some additional questions other items soon.
