### ISSUE TITLE
How to setup google authentication in Angular-Core-IdentityServer

### ISSUE THREAD

**Issue by DonKennethVitug** [elanderson/Angular-Core-IdentityServer#13]

**Comment by elanderson** [comment]
@DonKennethVitug I have an up coming blog post that covers adding Twitter, but Google would be very similar, but that isn't going to be out for a few weeks. If you check [this](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?tabs=aspnet1x) it walks you through adding login via Google. Just follow the steps in that doc on the IdentityApp and you should be good to go.

Reopen this issue if you have any more questions.
