### ISSUE TITLE
Forbidden_route & Unauthorized_route 

### ISSUE THREAD

**Issue by shaunPmulligan** [elanderson/Angular-Core-IdentityServer#20]
Hi, 

I cant seem to get the Forbidden Route and Unauthorized Route working. If I login and browse to /Fetchdata , i get the desired result, however if I then logout , the route disappears from the menu, however if I enter the route manually in the browser I was hoping it would redirect to the Unauthorized Route, however this does not happen, any ideas?

Thanks

**Comment by elanderson** [comment]
@shaunPmulligan, in order to do what you are looking for you, would need to use [CanActivate](https://angular.io/api/router/CanActivate) instead of just hiding the UI for the route.

**Comment by shaunPmulligan** [comment]
Thanks @elanderson, I will look into that, I was hoping I could just set trigger_authorization_result_event = false on the openIdImplicitFlowConfiguration and then it would kick off the code
`if (this.authConfiguration.trigger_authorization_result_event) {
									this.onAuthorizationResult.emit(AuthorizationResult.unauthorized);
								} else {
									this.router.navigate([this.authConfiguration.unauthorized_route]);
								}`

**Comment by elanderson** [comment]
@shaunPmulligan I hope that work for you. If you come up with another solution let us know what you find!
