### ISSUE TITLE
NodeInvocationException: No provider for PlatformRef!

### ISSUE THREAD

**Issue by kiranchandran** [elanderson/Angular-Core-IdentityServer#23]
Getting below error while running the angular application
NodeInvocationException: No provider for PlatformRef!
Error: No provider for PlatformRef!

**Comment by elanderson** [comment]
Try running the following command from a command prompt in the client application's directory.

`npm install
node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js
node node_modules/webpack/bin/webpack.js`

The comments on [this](post) talk about the same issue.

Reopen this issue if you still have problems.

**Comment by Jab0rnal** [comment]
Im getting the same error. Running the above command produces the following error:

> Could not install from "node_modules\webpack\bin\webpack.js" as it does not contain a package.json file

The link above is also dead.

Any ideas?
Cheer,
J

**Comment by kiranchandran** [comment]
@Jab0rnal  you need to follow the instructions in below post

https://stackoverflow.com/questions/47269890/upgrade-from-angular-4-to-5-nodeinvocationexception-no-provider-for-platformr

Also you may need to upgrade few of the packages. I have made it working using the below package.json

`{
  "name": "ProzesscenterAngular",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "test": "karma start ClientApp/test/karma.conf.js"
  },
  "dependencies": {
    "@angular/animations": "^5.0.2",
    "@angular/common": "^5.0.2",
    "@angular/compiler": "^5.0.2",
    "@angular/core": "^5.0.2",
    "@angular/forms": "^5.0.2",
    "@angular/http": "^5.0.2",
    "@angular/platform-browser": "^5.0.2",
    "@angular/platform-browser-dynamic": "^5.0.2",
    "@angular/platform-server": "^5.0.2",
    "@angular/router": "^5.0.2",
    "@types/webpack-env": "1.13.0",
    "angular-auth-oidc-client": "^3.0.4",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^3.0.1",
    "aspnet-webpack": "^2.0.1",
    "awesome-typescript-loader": "3.2.1",
    "bootstrap": "3.3.7",
    "css": "2.2.1",
    "css-loader": "0.28.4",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.9",
    "expose-loader": "0.7.3",
    "extract-text-webpack-plugin": "2.1.2",
    "file-loader": "0.11.2",
    "html-loader": "0.4.5",
    "isomorphic-fetch": "2.2.1",
    "jquery": "3.2.1",
    "json-loader": "0.5.4",
    "preboot": "4.5.2",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.5.2",
    "style-loader": "0.18.2",
    "to-string-loader": "1.1.5",
    "url-loader": "0.5.9",
    "webpack": "2.5.1",
    "webpack-hot-middleware": "2.18.2",
    "webpack-merge": "4.1.0",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^5.0.2",
    "@ngtools/webpack": "^1.8.2",
    "@types/chai": "4.0.1",
    "@types/jasmine": "2.5.53",
    "chai": "4.0.2",
    "jasmine-core": "2.6.4",
    "karma": "1.7.0",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.0",
    "karma-webpack": "2.0.3",
    "typescript": "^2.6.1"
  }
}`
