### ISSUE TITLE
Latest version not working 

### ISSUE THREAD

**Issue by sourabhacooli4** [elanderson/Angular-Core-IdentityServer#25]
Hello,

I am using your project but when I add (import { InputTextModule, DataTableModule, ButtonModule, DialogModule, DataListModule, DropdownModule, CalendarModule } from 'primeng/primeng')
so my pre render is not working.

Could you please look at this.

Regards
Sourabh Acooli

**Comment by elanderson** [comment]
Does the sample work before adding the imports for primeng?

**Comment by sourabhacooli4** [comment]
yes it is working before  adding primeng

**Comment by elanderson** [comment]
You might try adding primeng to the list of packages in webpack's vendor config (webpack.config.vendor.js) and from a CLI then run: node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js

Just to be safe you might want to also run the following command as well: node node_modules/webpack/bin/webpack.js

**Comment by sourabhacooli4** [comment]
Hello,

I can't under stand (CLI then run: node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js) because I am using Visual studio 2017. 
Could you please send me the step to proceed this process.

Regards
Sourabh Acooli

**Comment by elanderson** [comment]
CLI = Command Prompt. So in a command prompt run the two commands from above after making the vendor config change.

I'm closing this issue as this isn't a problem with the code as it stands in the repo.

**Comment by sourabhacooli4** [comment]
Hello,
When I try to add ( node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js) in cmd so I got this error.

Could you please go throw it. And try to give me a proper solution.

![browsererror](https://user-images.githubusercontent.com/11328871/34596395-59ebe698-f205-11e7-8b9e-26fc2045381b.png)
![error](https://user-images.githubusercontent.com/11328871/34596396-5a4f6ce0-f205-11e7-9ba8-9eb3e25f97aa.png)


Regards
Sourabh Acooli

**Comment by elanderson** [comment]
I'm sorry Sourabh, but I don't know exactly what is going on. If it were an issue in this repo I would find the time to dig into it, but since the repo works with no changes it is something to do with the code you have changed.

**Comment by sourabhacooli4** [comment]
Hello,

Please find the attachment of the project and please try to give me the
proper solution.

I am waiting for your positive reply.

Regards
Sourabh Acooli

​
 Angular-Core-IdentityServer-0.14.0.rar
<https://drive.google.com/file/d/1sb1__6rNF10muFzys-K6bws80lOyjieg/view?usp=drive_web>
​

**Comment by elanderson** [comment]
I'm sorry I don't have the capacity to debug your project. I do this stuff in my spare time and I don't have much of that.
