### ISSUE TITLE
Application not working using PRIMeng

### ISSUE THREAD

**Issue by sourabhacooli4** [elanderson/Angular-Core-IdentityServer#27]
Hello, When I use primeng in this application so my application is not working. Could you please check this out.

ERROR
Prerendering failed because of error: ReferenceError: Event is not defined

Regards
Sourabh Acooli

**Comment by elanderson** [comment]
Sorry @sourabhacooli4 but just like with issue #25 this isn't an issue with the code on this repo, but with changes, you have made and as such not something I will be able to fix for you.

**Comment by sourabhacooli4** [comment]
Hello,

Could you please try for your best because it is very helpful for my
project. And because of primeng it is helpful for all other person.


Regards
Sourabh Acooli
