### ISSUE TITLE
Upgraded Angular 5 not working in production Mode

### ISSUE THREAD

**Issue by tamizha09** [elanderson/Angular-Core-IdentityServer#29]
Hi,
Thanks for upgraded Angular 4 to Angular 5 But think is here,while publish or environment is in production,
webpack.config.js not able compile things properly which end up in error saying 
Module Not Found:"Cannot resolve - ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
     @ ./ClientApp/boot.browser.ts"

Have you come across the same if any

**Comment by elanderson** [comment]
@tamizha09 I haven't tried production mode. I will try and locate the issue, but might not be soon. If you happen to find a solution before I get to look at it I am happy to accept a PR!

**Comment by tamizha09** [comment]
Thanks for quick response.

I tried to find some links 

1.http://www.talkingdotnet.com/upgrade-angular-4-app-angular-5-visual-studio-2017/

2.https://github.com/long2know/angular-core-demo/ 
(Note: for running demo -> remove app_offline.htm in solution)

Above both sample works fine without server side pre rendering. but expected one is asp-prerender-module to load appsetting.json(appurl,identityurl).

if i include with pre-render-module and pre-render-data, it throws "No ResourceLoader implementation has been provided. Can't read the url "app.component.html"

Note: 
In rule in webpack.config,remove include: /ClientApp/,
my package.json
    "dependencies": {
    "@angular/animations": "5.1.1",
    "@angular/common": "5.1.1",
    "@angular/compiler": "5.1.1",
    "@angular/compiler-cli": "5.1.1",
    "@angular/core": "5.1.1",
    "@angular/forms": "5.1.1",
    "@angular/http": "5.1.1",
    "@angular/platform-browser": "5.1.1",
    "@angular/platform-browser-dynamic": "5.1.1",
    "@angular/platform-server": "5.1.1",
    "@angular/router": "5.1.1",
    "@types/webpack-env": "1.13.3",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "3.0.1",
    "aspnet-webpack": "2.0.1",
    "awesome-typescript-loader": "3.4.1",
    "bootstrap": "3.3.7",
    "css": "2.2.1",
    "css-loader": "0.28.7",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.12",
    "expose-loader": "0.7.4",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.6",
    "html-loader": "0.5.1",
    "isomorphic-fetch": "2.2.1",
    "jquery": "3.2.1",
    "json-loader": "0.5.7",
    "preboot": "4.5.2",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.5.5",
    "style-loader": "0.19.1",
    "to-string-loader": "1.1.5",
    "typescript": "2.6.2",
    "url-loader": "0.6.2",
    "webpack": "3.10.0",
    "webpack-hot-middleware": "2.21.0",
    "webpack-merge": "4.1.1",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ngtools/webpack": "1.8.0",
    "@types/chai": "4.0.10",
    "@types/jasmine": "2.8.2",
    "chai": "4.1.2",
    "jasmine-core": "2.8.0",
    "karma": "1.7.1",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.1",
    "karma-webpack": "2.0.9"
  }

Still finding solution for pre rendering from server side,it will be helpful if anything finding from your side

Thanks

**Comment by elanderson** [comment]
I was able to get publish to work, but I had to make some changes in the webpack.config.js file. Give this a shot and let me know if it works or not.

In the require section:
Before: `const AotPlugin = require('@ngtools/webpack').AotPlugin;`
After: `const AngularCompilerPlugin = require('@ngtools/webpack').AngularCompilerPlugin;`

Then in the rest of the file replace all of the `AotPlugin` with `AngularCompilerPlugin`.

**Comment by manmln** [comment]
Hi, when I published with this fix to Azure ClientApp page was not loaded - it generated error instead. This didn't happen with prior versions and it works OK locally.

**Comment by elanderson** [comment]
Is this the same issue that issue #32 was opened for?

**Comment by SimonSDA** [comment]
For those needing to get an Angular 4 app working, after a day of trying various things I had to do the reverse of @elanderson 's post and change (in webpack.config.js) line 4:

`const AotPlugin = require('@ngtools/webpack').AngularCompilerPlugin;`

to

`const AotPlugin = require('@ngtools/webpack').AotPlugin;`

For some reason the generated app had this as 'AngularCompilerPlugin'
