### ISSUE TITLE
ASP.NET core 2.1 support

### ISSUE THREAD

**Issue by rafsanulhasan** [elanderson/Angular-Core-IdentityServer#34]
@astegmaier @elanderson 
Please release a version developed with the new version of asp.net core 2.1

**Comment by elanderson** [comment]
@rafsanulhasan I will look into this. Last round it took a little while for Identity Server packages to get upgraded so it may be after that happens.

**Comment by elanderson** [comment]
@rafsanulhasan all 3 projects have been changed to target ASP.NET Core 2.1 via #35.
