### ISSUE TITLE
Fetch-data with server-side rendering (SSR)

### ISSUE THREAD

**Issue by astegmaier** [elanderson/Angular-Core-IdentityServer#8]
Hi! I stumbled across your blog posts and this repo in a search for examples about how to use IdentityServer to secure an angular app that uses server-side rendering (SSR). Thanks for putting it out there!

I set the repo up successfully on my OS X machine with [a few tweaks](https://github.com/astegmaier/Angular-Core-IdentityServer/commit/535b2a51ed31f775de12e3f80624430c0f8615f4), and I was able to successfully log in and call the protected api through the `fetch-data` component in the basic case--awesome!

One problem I came across was that triggering a hard refresh of after logging in does not appear to preserve the auth in server-side rendering. To repro, go to `http://localhost:5002/fetch-data`, log in so you can successfully see that data from the API endpoint, then turn off JavaScript and hit 'F5', and you should see the login screen instead of the data. 

Looking at how the auth tokens are stored on the client side (through `sessionStorage`), this isn't surprising (since `sessionStorage` won't be available on the server). I was curious if you'd figured out the optimal way to solve this (maybe `oidc-client` could be configured to store the token info in cookies and pass these up to the server, which could then read them and make them available to `oidc-client` running in node?). It seems like a tough problem for which I haven't yet found a great solution, and I was curious if you had. 

In any case, thanks again for sharing!

**Comment by elanderson** [comment]
@astegmaier thank you for sharing your changes to get it working on OS X.

Honestly, I haven't made it far enough past what is in the blog post to end determine what this issue is. Please let me know if you find a solution and I will do the same. Thank you for the feedback!

**Comment by astegmaier** [comment]
@elanderson - would you like me to submit the OSX fixes as a PR to take them into this branch?

I'll take a stab at the idea I suggested re: cookies and server storage. I have a similar concept working with the [angular-auth-oidc-client](https://github.com/damienbod/angular-auth-oidc-client) library in [this repo](https://github.com/astegmaier/angular-auth-oidc-client-SSR-test). On of the obstacles that I still don't have an idea how to solve is how to get the tokens that are passed in the callback to be visible on the server. It looks like both `oidc-client` and `angular-auth-oidc-client` are accepting the default `response_mode=fragment` which causes the tokens to be sent back to the client behind a hash (#), which doesn't get sent up to the server. Thus, if the callback page is being pre-rendered, there's no way for it to see the tokens. The next effect is that the user will see a flicker--the callback page is first sent down to the client (without any knowledge of the auth tokens), then the client-side JavaScript parses them and gives access to the protected resources, potentially modifying the UI. I'm not sure there is a way to solve this without writing my own library or modifying one of the existing ones. I'll keep you posted if I learn anything new!

**Comment by elanderson** [comment]
@astegmaier yes please do a PR. 

I am very interested to hear what you learn. Thank you for the links I am going to start following them. I am new to this space in general and I really appreciate your feedback as well as the insight into the issues I will have to have.
